/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import ChessScene from "./script/ChessScene"
import BoardSet from "./script/component/BoardSet"
import randomTouz from "./script/component/randomTouz"
import GridSet from "./script/component/GridSet"
import standMove from "./script/component/standMove"

export default class GameConfig {
    static init() {
        //注册Script或者Runtime引用
        let reg = Laya.ClassUtils.regClass;
		reg("script/ChessScene.js",ChessScene);
		reg("script/component/BoardSet.js",BoardSet);
		reg("script/component/randomTouz.js",randomTouz);
		reg("script/component/GridSet.js",GridSet);
		reg("script/component/standMove.js",standMove);
    }
}
GameConfig.width = 1280;
GameConfig.height = 640;
GameConfig.scaleMode ="showall";
GameConfig.screenMode = "horizontal";
GameConfig.alignV = "top";
GameConfig.alignH = "left";
GameConfig.startScene = "main.scene";
GameConfig.sceneRoot = "";
GameConfig.debug = true;
GameConfig.stat = false;
GameConfig.physicsDebug = false;
GameConfig.exportSceneToJson = true;

GameConfig.init();
