var s_iOffsetX=0,s_iOffsetY=0;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,4))})(navigator.userAgent||
navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}function isIOS(){for(var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");a.length;)if(navigator.platform===a.pop())return s_bIsIphone=!0;return s_bIsIphone=!1}window.addEventListener("orientationchange",onOrientationChange);
function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}
function getSize(a){var c=a.toLowerCase(),b=window.document,d=b.documentElement;if(void 0===window["inner"+a])a=d["client"+a];else if(window["inner"+a]!=d["client"+a]){var f=b.createElement("body");f.id="vpw-test-b";f.style.cssText="overflow:scroll";var e=b.createElement("div");e.id="vpw-test-d";e.style.cssText="position:absolute;top:-1000px";e.innerHTML="<style>@media("+c+":"+d["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+c+":7px!important}}</style>";f.appendChild(e);d.insertBefore(f,b.head);
a=7==e["offset"+a]?d["client"+a]:window["inner"+a];d.removeChild(f)}else a=window["inner"+a];return a}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a;a=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var c=getSize("Width");s_iScaleFactor=Math.min(a/CANVAS_HEIGHT,c/CANVAS_WIDTH);var b=CANVAS_WIDTH*s_iScaleFactor,d=CANVAS_HEIGHT*s_iScaleFactor,f;d<a?(f=a-d,d+=f,b+=CANVAS_WIDTH/CANVAS_HEIGHT*f):b<c&&(f=c-b,b+=f,d+=CANVAS_HEIGHT/CANVAS_WIDTH*f);f=a/2-d/2;var e=c/2-b/2,g=CANVAS_WIDTH/b;if(e*g<-EDGEBOARD_X||f*g<-EDGEBOARD_Y)s_iScaleFactor=Math.min(a/
(CANVAS_HEIGHT-2*EDGEBOARD_Y),c/(CANVAS_WIDTH-2*EDGEBOARD_X)),b=CANVAS_WIDTH*s_iScaleFactor,d=CANVAS_HEIGHT*s_iScaleFactor,f=(a-d)/2,e=(c-b)/2,g=CANVAS_WIDTH/b;s_iOffsetX=-1*e*g;s_iOffsetY=-1*f*g;0<=f&&(s_iOffsetY=0);0<=e&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oHelpPanel&&s_oHelpPanel.refreshButtonPos(s_iOffsetX,s_iOffsetY);s_bMobile&&!s_bIsIphone?($("#canvas").css("width",b+
"px"),$("#canvas").css("height",d+"px")):(s_oStage.canvas.width=b,s_oStage.canvas.height=d,s_oStage.scaleX=s_oStage.scaleY=Math.min(b/CANVAS_WIDTH,d/CANVAS_HEIGHT));0>f?$("#canvas").css("top",f+"px"):$("#canvas").css("top","0px");$("#canvas").css("left",e+"px")}}function inIframe(){try{return window.self!==window.top}catch(a){return!0}}
function createBitmap(a,c,b){var d=new createjs.Bitmap(a),f=new createjs.Shape;c&&b?f.graphics.beginFill("#fff").drawRect(-c/2,-b/2,c,b):f.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);d.hitArea=f;return d}function createSprite(a,c,b,d,f,e){a=null!==c?new createjs.Sprite(a,c):new createjs.Sprite(a);c=new createjs.Shape;c.graphics.beginFill("#000000").drawRect(-b,-d,f,e);a.hitArea=c;return a}
function randomFloatBetween(a,c,b){"undefined"===typeof b&&(b=2);return parseFloat(Math.min(a+Math.random()*(c-a),c).toFixed(b))}function shuffle(a){for(var c=a.length,b,d;0!==c;)d=Math.floor(Math.random()*c),--c,b=a[c],a[c]=a[d],a[d]=b;return a}function formatTime(a){a/=1E3;var c=Math.floor(a/60);a=parseFloat(a-60*c).toFixed(1);var b="",b=10>c?b+("0"+c+":"):b+(c+":");return 10>a?b+("0"+a):b+a}function degreesToRadians(a){return a*Math.PI/180}
function checkRectCollision(a,c){var b,d;b=getBounds(a,.9);d=getBounds(c,.98);return calculateIntersection(b,d)}function calculateIntersection(a,c){var b,d,f,e,g,k,h,l;b=a.x+(f=a.width/2);d=a.y+(e=a.height/2);g=c.x+(k=c.width/2);h=c.y+(l=c.height/2);b=Math.abs(b-g)-(f+k);d=Math.abs(d-h)-(e+l);return 0>b&&0>d?(b=Math.min(Math.min(a.width,c.width),-b),d=Math.min(Math.min(a.height,c.height),-d),{x:Math.max(a.x,c.x),y:Math.max(a.y,c.y),width:b,height:d,rect1:a,rect2:c}):null}
function getBounds(a,c){var b={x:Infinity,y:Infinity,width:0,height:0};if(a instanceof createjs.Container){b.x2=-Infinity;b.y2=-Infinity;var d=a.children,f=d.length,e,g;for(g=0;g<f;g++)e=getBounds(d[g],1),e.x<b.x&&(b.x=e.x),e.y<b.y&&(b.y=e.y),e.x+e.width>b.x2&&(b.x2=e.x+e.width),e.y+e.height>b.y2&&(b.y2=e.y+e.height);Infinity==b.x&&(b.x=0);Infinity==b.y&&(b.y=0);Infinity==b.x2&&(b.x2=0);Infinity==b.y2&&(b.y2=0);b.width=b.x2-b.x;b.height=b.y2-b.y;delete b.x2;delete b.y2}else{var k,h;a instanceof createjs.Bitmap?
(f=a.sourceRect||a.image,g=f.width*c,k=f.height*c):a instanceof createjs.Sprite?a.spriteSheet._frames&&a.spriteSheet._frames[a.currentFrame]&&a.spriteSheet._frames[a.currentFrame].image?(f=a.spriteSheet.getFrame(a.currentFrame),g=f.rect.width,k=f.rect.height,d=f.regX,h=f.regY):(b.x=a.x||0,b.y=a.y||0):(b.x=a.x||0,b.y=a.y||0);d=d||0;g=g||0;h=h||0;k=k||0;b.regX=d;b.regY=h;f=a.localToGlobal(0-d,0-h);e=a.localToGlobal(g-d,k-h);g=a.localToGlobal(g-d,0-h);d=a.localToGlobal(0-d,k-h);b.x=Math.min(Math.min(Math.min(f.x,
e.x),g.x),d.x);b.y=Math.min(Math.min(Math.min(f.y,e.y),g.y),d.y);b.width=Math.max(Math.max(Math.max(f.x,e.x),g.x),d.x)-b.x;b.height=Math.max(Math.max(Math.max(f.y,e.y),g.y),d.y)-b.y}return b}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var c=document.createEvent("MouseEvents");c.initEvent("click",!0,!0);a.dispatchEvent(c)}}};
(function(){function a(a){var d={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;a.type in d?document.body.className=d[a.type]:(document.body.className=this[c]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var c="hidden";c in document?document.addEventListener("visibilitychange",a):(c="mozHidden")in document?document.addEventListener("mozvisibilitychange",a):(c="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",a):(c="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();function playSound(a,c,b){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?createjs.Sound.play(a,{loop:b,volume:c}):null}function stopSound(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.stop()}
function setVolume(a,c){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)a.volume=c}function setMute(a,c){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.setMute(c)}function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}function getParamValue(a){for(var c=window.location.search.substring(1).split("&"),b=0;b<c.length;b++){var d=c[b].split("=");if(d[0]==a)return d[1]}}
function distanceV2(a,c){var b=a.x-c.x,d=a.y-c.y;return Math.sqrt(b*b+d*d)}function randomRange(a,c){return Math.floor(Math.random()*(c-a))+a}function saveItem(a,c){localStorage.setItem(a,c)}function getItem(a){return localStorage.getItem(a)}function clearAllItem(){localStorage.clear()}function centerBetweenPointsV2(a,c){var b=new CVector2;b.set(.5*(a.getX()+c.getX()),.5*(a.getY()+c.getY()));return b}function perpProductV2(a,c){return a.getX()*c.getY()-a.getY()*c.getX()}
function dotProductV2(a,c){return a.getX()*c.getX()+a.getY()*c.getY()}function inSegment(a,c){if(c.getPointA().x!=c.getPointB().getX()){if(c.getPointA().getX()<=a.getX()&&a.getX()<=c.getPointB().getX()||c.getPointA().getX()>=a.getX()&&a.getX()>=c.getPointB().getX())return 1}else if(c.getPointA().getY()<=a.getY()&&a.getY()<=c.getPointB().getY()||c.getPointA().getY()>=a.getY()&&a.getY()>=c.getPointB().getY())return 1;return 0}
function intersect2D_Segments(a,c,b,d){var f=new CVector2,e=new CVector2,g=new CVector2;f.set(a.getPointB().getX()-a.getPointA().getX(),a.getPointB().getY()-a.getPointA().getY());e.set(c.getPointB().getX()-c.getPointA().getX(),c.getPointB().getY()-c.getPointA().getY());g.set(a.getPointA().getX()-c.getPointA().getX(),a.getPointA().getY()-c.getPointA().getY());var k=perpProductV2(f,e);if(1E-8>Math.abs(k)){f=dotProductV2(f,f);k=dotProductV2(e,e);if(0==f&&0==k){if(a.getPointA().getX()!=c.getPointA().getX()||
a.getPointA().getY()!=c.getPointA().getY())return 0;a.getPointA();return 1}if(0==f){if(0==inSegment(a.getPointA(),c))return 0;a.getPointA();return 1}if(0==k){if(0==inSegment(c.getPointA(),a))return 0;c.getPointA();return 1}f=new CVector2;f.set(a.getPointB().getX()-c.getPointA().getX(),a.getPointB().getY()-c.getPointA().getY());0!=e.getX()?(a=g.getX()/e.getX(),g=f.getX()/e.getX()):(a=g.getY()/e.getY(),g=f.getY()/e.getY());a>g&&(f=a,a=g,g=f);if(1<a||0>g)return 0;a=0>a?0:a;g=1<g?1:g;if(a==g)return b.set(c.getPointA().getX()+
a*e.getX(),c.getPointA().getY()+a*e.getY()),1;b.set(c.getPointA().getX()+a*e.getX(),c.getPointA().getY()+a*e.getY());d.set(c.getPointA().getX()+g*e.getX(),c.getPointA().getY()+g*e.getY());return 2}c=perpProductV2(e,g)/k;if(0>c||1<c)return 0;d=perpProductV2(f,g)/k;if(0>d||1<d)return 0;b.set(a.getPointA().getX()+c*f.getX(),a.getPointA().getY()+c*f.getY());trace("####################");trace("S1.getPointA().getX() + sI * u.x: "+b.getX());return 1}
function getRandomColor(){return"rgba("+(Math.floor(127*Math.random()+255)-127)+","+(Math.floor(127*Math.random()+255)-127)+","+(Math.floor(127*Math.random()+255)-127)+",1)"}function colorLuminance(a,c){a=String(a).replace(/[^0-9a-f]/gi,"");6>a.length&&(a=a[0]+a[0]+a[1]+a[1]+a[2]+a[2]);c=c||0;var b="#",d,f;for(f=0;3>f;f++)d=parseInt(a.substr(2*f,2),16),d=Math.round(Math.min(Math.max(0,d+d*c),255)).toString(16),b+=("00"+d).substr(d.length);return b}function linearLerp(a,c,b){return(1-b)*a+b*c}
function colorLerpShape(a,c,b,d,f,e,g,k,h,l){var m={},n=createjs.Tween.get(c,{override:!0}).wait(d).to({lerp:b.lerp},f,g).call(function(){null!==l&&l();createjs.Tween.removeTweens(n)}).addEventListener("change",function(){var a=parseInt(linearLerp(c.r,b.r,c.lerp)),f=parseInt(linearLerp(c.g,b.g,c.lerp)),d=parseInt(linearLerp(c.b,b.b,c.lerp));m[h]="rgba("+a+","+f+","+d+",1)";e(k,m)})}
function hexToRgb(a){return(a=/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(a))?{r:parseInt(a[1],16),g:parseInt(a[2],16),b:parseInt(a[3],16)}:null}
function BoundingBoxEdge(a){for(var c=a[0].getPointA().getX(),b=a[0].getPointA().getY(),d=a[0].getPointA().getX(),f=a[0].getPointA().getY(),e=1;e<a.length;e++)a[e].getPointA().getX()<c?c=a[e].getPointA().getX():a[e].getPointA().getX()>d&&(d=a[e].getPointA().getX()),a[e].getPointA().getY()<b?b=a[e].getPointA().getY():a[e].getPointA().getY()>f&&(f=a[e].getPointA().getY());return{xMin:c,yMin:b,xMax:d,yMax:f}}
function BoundingBox(a){for(var c=a[0].x,b=a[0].y,d=a[0].x,f=a[0].y,e=1;e<a.length;e++)a[e].x<c?c=a[e].x:a[e].x>d&&(d=a[e].x),a[e].y<b?b=a[e].y:a[e].y>f&&(f=a[e].y);return{xMin:c,yMin:b,xMax:d,yMax:f}}
function CSpriteLibrary(){var a,c,b,d,f,e;this.init=function(g,k,h){b=c=0;d=g;f=k;e=h;a={}};this.addSprite=function(f,b){a.hasOwnProperty(f)||(a[f]={szPath:b,oSprite:new Image},c++)};this.getSprite=function(f){return a.hasOwnProperty(f)?a[f].oSprite:null};this._onSpritesLoaded=function(){f.call(e)};this._onSpriteLoaded=function(){d.call(e);++b==c&&this._onSpritesLoaded()};this.loadSprites=function(){for(var f in a)a[f].oSprite.oSpriteLibrary=this,a[f].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[f].oSprite.src=a[f].szPath};this.getNumSprites=function(){return c}}
var CANVAS_WIDTH=840,CANVAS_HEIGHT=1360,CANVAS_WIDTH_HALF=.5*CANVAS_WIDTH,CANVAS_HEIGHT_HALF=.5*CANVAS_HEIGHT,EDGEBOARD_X=72,EDGEBOARD_Y=170,CONFIRMATION_EXIT=0,CONFIRMATION_RESET=1,DISABLE_SOUND_MOBILE=!1,FONT_GAME="Odin-Bold",TEXT_COLOR="#fff",TEXT_COLOR_STROKE="#555555",TEXT_COLOR_BEST_SORE="#fff",FPS_TIME=1E3/30,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,STATE_INIT=0,STATE_PLAY=1,STATE_FINISH=2,STATE_PAUSE=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=
4,ON_DRAG_END=5,ON_BUT_NO_DOWN=6,ON_BUT_YES_DOWN=7,NUM_OF_EDGES_FOR_STACK=4,SHOW_EDGES=!0,SHOW_FILL=!0,LEFT_UP=3,RIGHT_UP=2,LEFT_DOWN=1,RIGHT_DOWN=0,NO_DIR=4,EDGE_RIGHT_UP=0,EDGE_RIGHT_DOWN=1,EDGE_LEFT_DOWN=2,EDGE_LEFT_UP=3,STACK_DIRECTIONS={x:.5,y:.5},MS_FADE_ANIM=250,MS_SCROLL_CONTAINER_STACK=750,MS_PERFECT_TEXT=1E3,PERFECT_TEXT_START_POINT={x:CANVAS_WIDTH_HALF,y:CANVAS_HEIGHT-150},PERFECT_TEXT_END_POINT={x:CANVAS_WIDTH_HALF,y:CANVAS_HEIGHT-300},MS_WAIT_SHOW_GAME_OVER_PANEL=500,PLANES_COLOR_1={r:200,
g:0,b:0,a:1},LINES_COLOR_1={r:0,g:200,b:0,a:1},PLANES_COLOR_2={r:0,g:0,b:200,a:1},LINES_COLOR_2={r:255,g:255,b:0,a:1},MS_TIME_ZOOM_OUT=1E3,MS_TIME_PERFECT_HIT=500,CONTAINER_STACK_POS={x:CANVAS_WIDTH_HALF,y:CANVAS_HEIGHT_HALF},LINES_WIDTH=1,ANGLE_STACK=Math.PI/180*35,DEFAULT_DIR={x:Math.cos(ANGLE_STACK),y:Math.sin(ANGLE_STACK)},DIRECTION_STACKS=[DEFAULT_DIR,{x:-DEFAULT_DIR.x,y:DEFAULT_DIR.y},{x:DEFAULT_DIR.x,y:-DEFAULT_DIR.y},{x:-DEFAULT_DIR.x,y:-DEFAULT_DIR.y},{x:0,y:0}],STACK_DIMENSION={x:200,y:140},
STACK_DEPTH_SIZE=50,STACK_HEIGHT_OFFSET=100,STACK_HEIGHT_OFFSET_HALF=.5*STACK_HEIGHT_OFFSET,STACKS_DISTANCE_OFFSET=300,PERFECT_RANGE=10,DEFAULT_COLOR=["#cc0000","#00cc00","#0000cc","#ffff00"],DEPTH_LUMINANCE=-.2,COLOR_GRADIENTS_STACKS="#FF5858 #FF6058 #FF6958 #FF7158 #FF7A58 #FF8358 #FF8B58 #FF9458 #FF9D58 #FFA558 #FFAE58 #FFB658 #FFBF58 #FFC858 #FFD058 #FFD958 #FFE258 #F4E358 #EAE559 #DFE659 #D5E85A #CAEA5B #C0EB5B #B5ED5C #ABEF5D #A0F05D #96F25E #8BF35E #81F55F #76F760 #6CF860 #61FA61 #57FC62 #5AF26B #5DE975 #60E07E #64D788 #67CE91 #6AC49B #6DBBA4 #71B2AE #74A9B7 #77A0C1 #7A96CA #7E8DD4 #8184DD #847BE7 #8772F0 #8B69FA #9267EF #9A66E4 #A265D9 #A964CE #B163C4 #B962B9 #C161AE #C85FA3 #D05E98 #D85D8E #E05C83 #E75B78 #EF5A6D #F75962 #FF5858".split(" "),
SHOW_CUT_EDGES=!1,STACKS_LIMIT_POSITION=[{x:966,y:620},{x:425,y:598},{x:942,y:236.5},{x:426,y:242}],STACKS_START_POSITION=[{x:426,y:242,dir:LEFT_UP},{x:942,y:236.5,dir:LEFT_DOWN}],START_EDGES_POSITION=[{startX:0,startY:-STACK_DIMENSION.y,endX:STACK_DIMENSION.x,endY:0,type:EDGE_RIGHT_UP},{startX:STACK_DIMENSION.x,startY:0,endX:0,endY:STACK_DIMENSION.y,type:EDGE_RIGHT_DOWN},{startX:0,startY:STACK_DIMENSION.y,endX:-STACK_DIMENSION.x,endY:0,type:EDGE_LEFT_DOWN},{startX:-STACK_DIMENSION.x,startY:0,endX:0,
endY:-STACK_DIMENSION.y,type:EDGE_LEFT_UP}];TEXT_GAMEOVER="GAME OVER";TEXT_COMMANDS="CONTROLS";TEXT_COMPLETE="COMPLETE";TEXT_CREDITS_DEVELOPED="DEVELOPED BY";TEXT_SCORE="SCORE";TEXT_BEST_SCORE="BEST SCORE";TEXT_ARE_SURE="ARE YOU SURE?";TEXT_CONTROLS="CONTROLS";TEXT_PERFECT="PERFECT";TEXT_SHARE_IMAGE="200x200.jpg";TEXT_SHARE_TITLE="Congratulations!";TEXT_SHARE_MSG1="You collected <strong>";TEXT_SHARE_MSG2=" points</strong>!<br><br>Share your score with your friends!";TEXT_SHARE_SHARE1="My score is ";
TEXT_SHARE_SHARE2=" points! Can you do better?";
function CPreloader(){var a,c,b,d,f,e,g,k,h;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.png");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();h=new createjs.Container;s_oStage.addChild(h)};this.unload=function(){h.removeAllChildren()};this.hide=function(){var a=this;setTimeout(function(){createjs.Tween.get(e).to({alpha:1},500).call(function(){a.unload();
s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){g=new createjs.Shape;g.graphics.beginFill(COLOR_GRADIENTS_STACKS[Math.floor(Math.random()*COLOR_GRADIENTS_STACKS.length)]).drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);h.addChild(g);k=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));h.addChild(k);var l=s_oSpriteLibrary.getSprite("progress_bar");d=createBitmap(l);d.x=CANVAS_WIDTH/
2-l.width/2;d.y=CANVAS_HEIGHT-200;h.addChild(d);a=l.width;c=l.height;f=new createjs.Shape;f.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(d.x,d.y,1,c);h.addChild(f);d.mask=f;b=new createjs.Text("","30px "+FONT_GAME,"#fff");b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT-200;b.textBaseline="alphabetic";b.textAlign="center";h.addChild(b);e=new createjs.Shape;e.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);e.alpha=0;h.addChild(e)};this.refreshLoader=function(e){b.text=e+"%";f.graphics.clear();
e=Math.floor(e*a/100);f.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(d.x,d.y,e,c)};this._init()}
function CMain(a){var c,b=0,d=0,f=STATE_LOADING,e,g,k;this.initContainer=function(){var a=document.getElementById("canvas");s_oStage=new createjs.Stage(a);createjs.Touch.enable(s_oStage);s_oStage.preventSelection=!1;s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(a){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.setFPS(30);navigator.userAgent.match(/Windows Phone/i)&&
(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;g=new CPreloader;c=!0};this.soundLoaded=function(){b++;g.refreshLoader(Math.floor(b/d*100));if(b===d){g.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundTrack=createjs.Sound.play("soundtrack",{loop:-1});this.gotoMenu()}};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=["mp3"],createjs.Sound.addEventListener("fileload",
createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/click.ogg","click"),createjs.Sound.registerSound("./sounds/soundtrack.ogg","soundtrack"),createjs.Sound.registerSound("./sounds/cut.ogg","cut"),createjs.Sound.registerSound("./sounds/game_over.ogg","game_over"),createjs.Sound.registerSound("./sounds/perfect.ogg","perfect")):(createjs.Sound.alternateExtensions=["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/click.mp3",
"click"),createjs.Sound.registerSound("./sounds/soundtrack.mp3","soundtrack"),createjs.Sound.registerSound("./sounds/cut.mp3","cut"),createjs.Sound.registerSound("./sounds/game_over.mp3","game_over"),createjs.Sound.registerSound("./sounds/perfect.mp3","perfect")),d+=5)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("but_info",
"./sprites/but_info.png");s_oSpriteLibrary.addSprite("but_restart_small","./sprites/but_restart_small.png");s_oSpriteLibrary.addSprite("but_yes","./sprites/but_yes.png");s_oSpriteLibrary.addSprite("but_home","./sprites/but_home.png");s_oSpriteLibrary.addSprite("but_restart","./sprites/but_restart.png");s_oSpriteLibrary.addSprite("but_start","./sprites/but_start.png");s_oSpriteLibrary.addSprite("but_no","./sprites/but_no.png");s_oSpriteLibrary.addSprite("but_fullscreen","./sprites/but_fullscreen.png");
s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.png");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("logo_ctl","./sprites/logo_ctl.png");s_oSpriteLibrary.addSprite("logo_menu","./sprites/logo_menu.png");s_oSpriteLibrary.addSprite("bg_score","./sprites/bg_score.png");s_oSpriteLibrary.addSprite("bg_bestscore","./sprites/bg_bestscore.png");
d+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){b++;g.refreshLoader(Math.floor(b/d*100));if(b===d){g.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundTrack=createjs.Sound.play("soundtrack",{loop:-1});this.gotoMenu()}};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this.preloaderReady=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();this._loadImages();c=!0};
this.gotoMenu=function(){new CMenu;f=STATE_MENU};this.gotoGame=function(){k=new CGame(e);f=STATE_GAME};this.gotoHelp=function(){new CHelp;f=STATE_HELP};this.gotoCongratulations=function(a,b){new CCongratulations(a,b);f=STATE_MENU};this.stopUpdate=function(){c=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block");createjs.Sound.setMute(!0)};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();c=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none");s_bAudioActive&&
createjs.Sound.setMute(!1)};this._update=function(a){if(!1!==c){var b=(new Date).getTime();s_iTimeElaps=b-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=b;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);f===STATE_GAME&&k.update();s_oStage.update(a)}};s_oMain=this;e=a;this.initContainer()}
var s_bMobile,s_bAudioActive=!0,s_bFullscreen=!1,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oAdsLevel=1,s_iBestScore,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundTrack;
function CTextButton(a,c,b,d,f,e,g,k){var h,l,m,n;this._init=function(a,f,b,c,d,e,g){h=[];l=[];var k=createBitmap(b),v=Math.ceil(g/20),A=new createjs.Text(c,"bold "+g+"px "+d,"#000000");A.textAlign="center";A.textBaseline="alphabetic";var x=A.getBounds();A.x=b.width/2+v;A.y=Math.floor(b.height/2)+x.height/3+v;c=new createjs.Text(c,"bold "+g+"px "+d,e);c.textAlign="center";c.textBaseline="alphabetic";x=c.getBounds();c.x=b.width/2;c.y=Math.floor(b.height/2)+x.height/3;m=new createjs.Container;m.x=a;
m.y=f;m.regX=b.width/2;m.regY=b.height/2;m.addChild(k,A,c);s_bMobile||(m.cursor="pointer");n.addChild(m);this._initListener()};this.unload=function(){m.off("mousedown");m.off("pressup");n.removeChild(m)};this.setVisible=function(a){m.visible=a};this._initListener=function(){oParent=this;m.on("mousedown",this.buttonDown);m.on("pressup",this.buttonRelease)};this.addEventListener=function(a,f,b){h[a]=f;l[a]=b};this.buttonRelease=function(){m.scaleX=1;m.scaleY=1;playSound("click",1,0);h[ON_MOUSE_UP]&&
h[ON_MOUSE_UP].call(l[ON_MOUSE_UP])};this.buttonDown=function(){m.scaleX=.9;m.scaleY=.9;h[ON_MOUSE_DOWN]&&h[ON_MOUSE_DOWN].call(l[ON_MOUSE_DOWN])};this.setPosition=function(a,f){m.x=a;m.y=f};this.setX=function(a){m.x=a};this.setY=function(a){m.y=a};this.getButtonImage=function(){return m};this.getX=function(){return m.x};this.getY=function(){return m.y};n=k;this._init(a,c,b,d,f,e,g);return this}
function CToggle(a,c,b,d,f){var e,g,k,h,l;this._init=function(a,f,b,c,d){l=void 0!==d?d:s_oStage;g=[];k=[];d=new createjs.SpriteSheet({images:[b],frames:{width:b.width/2,height:b.height,regX:b.width/2/2,regY:b.height/2},animations:{state_true:[0],state_false:[1]}});e=c;h=createSprite(d,"state_"+e,b.width/2/2,b.height/2,b.width/2,b.height);h.x=a;h.y=f;h.stop();s_bMobile||(h.cursor="pointer");l.addChild(h);this._initListener()};this.unload=function(){h.off("mousedown",this.buttonDown);h.off("pressup",
this.buttonRelease);l.removeChild(h)};this._initListener=function(){h.on("mousedown",this.buttonDown);h.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,f){g[a]=b;k[a]=f};this.setCursorType=function(a){h.cursor=a};this.setActive=function(a){e=a;h.gotoAndStop("state_"+e)};this.buttonRelease=function(){h.scaleX=1;h.scaleY=1;playSound("click",1,0);e=!e;h.gotoAndStop("state_"+e);g[ON_MOUSE_UP]&&g[ON_MOUSE_UP].call(k[ON_MOUSE_UP],e)};this.buttonDown=function(){h.scaleX=.9;h.scaleY=
.9;g[ON_MOUSE_DOWN]&&g[ON_MOUSE_DOWN].call(k[ON_MOUSE_DOWN])};this.setPosition=function(a,b){h.x=a;h.y=b};this._init(a,c,b,d,f)}
function CGfxButton(a,c,b,d){var f,e,g,k,h,l,m,n=!1,q;this._init=function(a,b,c){f=[];e=[];g=createBitmap(c);g.x=a;g.y=b;l=h=1;g.regX=c.width/2;g.regY=c.height/2;s_bMobile||(g.cursor="pointer");q.addChild(g);this._initListener()};this.unload=function(){g.off("mousedown",this.buttonDown);g.off("pressup",this.buttonRelease);q.removeChild(g)};this.setVisible=function(a){g.visible=a};this.setCursorType=function(a){g.cursor=a};this._initListener=function(){g.on("mousedown",this.buttonDown);g.on("pressup",
this.buttonRelease)};this.addEventListener=function(a,b,c){f[a]=b;e[a]=c};this.addEventListenerWithParams=function(a,b,c,d){f[a]=b;e[a]=c;k=d};this.buttonRelease=function(){n||(g.scaleX=0<h?1:-1,g.scaleY=1,playSound("click",1,0),f[ON_MOUSE_UP]&&f[ON_MOUSE_UP].call(e[ON_MOUSE_UP],k))};this.buttonDown=function(){n||(g.scaleX=0<h?.9:-.9,g.scaleY=.9,f[ON_MOUSE_DOWN]&&f[ON_MOUSE_DOWN].call(e[ON_MOUSE_DOWN],k))};this.rotation=function(a){g.rotation=a};this.getButton=function(){return g};this.setPosition=
function(a,b){g.x=a;g.y=b};this.setX=function(a){g.x=a};this.setY=function(a){g.y=a};this.getButtonImage=function(){return g};this.block=function(a){n=a;g.scaleX=h;g.scaleY=l};this.setScaleX=function(a){h=g.scaleX=a};this.getX=function(){return g.x};this.getY=function(){return g.y};this.pulseAnimation=function(){createjs.Tween.get(g).to({scaleX:.9*h,scaleY:.9*l},850,createjs.Ease.quadOut).to({scaleX:h,scaleY:l},650,createjs.Ease.quadIn).call(function(){m.pulseAnimation()})};this.trebleAnimation=function(){createjs.Tween.get(g).to({rotation:5},
75,createjs.Ease.quadOut).to({rotation:-5},140,createjs.Ease.quadIn).to({rotation:0},75,createjs.Ease.quadIn).wait(750).call(function(){m.trebleAnimation()})};this.removeAllTweens=function(){createjs.Tween.removeTweens(g)};q=d;this._init(a,c,b);m=this;return this}
function CMenu(){var a,c,b,d,f,e,g,k,h,l,m,n,q,p,t;this._init=function(){s_iBestScore=getItem("box_best_score");null===s_iBestScore&&(s_iBestScore=0);var u=Math.floor(Math.random()*COLOR_GRADIENTS_STACKS.length);g=new createjs.Shape;g.graphics.beginFill(COLOR_GRADIENTS_STACKS[u]).drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(g);k=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(k);p=new createjs.Container;s_oStage.addChild(p);for(var r=[],w=0;w<NUM_OF_EDGES_FOR_STACK;w++)r.push(new CEdge(1.3*
START_EDGES_POSITION[w].startX,1.3*START_EDGES_POSITION[w].startY,1.3*START_EDGES_POSITION[w].endX,1.3*START_EDGES_POSITION[w].endY));u+=32;u>=COLOR_GRADIENTS_STACKS.length&&(u-=COLOR_GRADIENTS_STACKS.length);var w=CANVAS_WIDTH_HALF-122,y=CANVAS_HEIGHT_HALF+30;new CStack({x:w+(1.3*DIRECTION_STACKS[2].x*STACK_DIMENSION.x+STACK_DEPTH_SIZE-19.5),y:y+(1.3*DIRECTION_STACKS[2].y*STACK_DIMENSION.y-12*1.3)-STACK_DEPTH_SIZE,dir:NO_DIR},{line:COLOR_GRADIENTS_STACKS[u],plane:COLOR_GRADIENTS_STACKS[u],width:LINES_WIDTH,
depth:null},r,p);new CStack({x:w,y:y,dir:NO_DIR},{line:COLOR_GRADIENTS_STACKS[u],plane:COLOR_GRADIENTS_STACKS[u],width:LINES_WIDTH,depth:null},r,p);r=s_oSpriteLibrary.getSprite("logo_menu");t=createBitmap(r);t.x=CANVAS_WIDTH_HALF+56;t.y=.5*-r.width;t.regX=.5*r.width;t.regY=.5*r.height;t.rotation=-15;s_oStage.addChild(t);r=s_oSpriteLibrary.getSprite("but_play");b=CANVAS_WIDTH/2;d=CANVAS_HEIGHT-435;h=new CGfxButton(b,d,r,s_oStage);h.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);h.pulseAnimation();
if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)r=s_oSpriteLibrary.getSprite("audio_icon"),f=CANVAS_WIDTH-r.height/2-15,e=r.height/2+15,n=new CToggle(f,e,r,s_bAudioActive,s_oStage),n.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);r=s_oSpriteLibrary.getSprite("but_info");a=r.height/2+17;c=r.height/2+15;l=new CGfxButton(a,c,r,s_oStage);l.addEventListener(ON_MOUSE_UP,this._onButInfoRelease,this);q=new createjs.Container;s_oStage.addChild(q);m=new createjs.Shape;m.graphics.beginFill("black").drawRect(0,
0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(m);createjs.Tween.get(t).wait(300).to({rotation:0},1E3,createjs.Ease.cubicOut);createjs.Tween.get(t).wait(300).to({y:CANVAS_HEIGHT_HALF-96},1E3,createjs.Ease.bounceOut);createjs.Tween.get(m,{override:!0}).to({alpha:0},500,createjs.Ease.cubicOut).call(function(){m.visible=!1});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.refreshButtonPos=function(b,d){l.setPosition(a+b,c+d);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||n.setPosition(f-b,d+e)};this.unload=
function(){h.unload();h=null;l.unload();l=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)n.unload(),n=null;s_oStage.removeAllChildren();s_oMenu=null};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onButInfoRelease=function(){new CCreditsPanel};this._onButPlayRelease=function(){this.fadeAnim()};this.fadeAnim=function(){var a=this;m.visible=!0;createjs.Tween.get(m,{override:!0}).to({alpha:1},MS_FADE_ANIM,createjs.Ease.cubicIn).call(function(){a.unload();
s_oMain.gotoGame()})};s_oMenu=this;this._init()}var s_oMenu=null;
function CGame(a){var c,b;function d(a){g||h!==STATE_PLAY||32!==a.keyCode||(s_oGame.onMouseDown(),g=!0);a.preventDefault();return!1}function f(a){32===a.keyCode&&(g=!1);a.preventDefault();return!1}var e=!0,g=!1,k=0,h=STATE_PAUSE,l=1,m,n,q,p=0,t,u,r,w,y,z,v,A,x;this._init=function(){$(s_oMain).trigger("start_session");$(s_oMain).trigger("start_level",1);x=[];this.restartColorGrandients();u=new createjs.Shape;u.graphics.beginFill(COLOR_GRADIENTS_STACKS[q]).drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);u.cache(0,
0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(u);var a=s_oSpriteLibrary.getSprite("bg_game");r=createBitmap(a);s_oStage.addChild(r);r.cache(0,0,a.width,a.height);y=new createjs.Container;y.tickChildren=!1;this.resetContainerStacks();s_oStage.addChild(y);A=new createjs.Shape;A.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);A.on("mousedown",this.onMouseDown);s_oStage.addChild(A);t=new CInterface;t.refreshScoreText(k);t.refreshBestScore(s_iBestScore,!1);this.createStartStacks();
w=new createjs.Shape;w.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);b=c=0;s_oStage.addChild(w);s_bMobile||(document.onkeydown=d,document.onkeyup=f);this.startFade()};this.restartColorGrandients=function(){n=Math.floor(Math.random()*COLOR_GRADIENTS_STACKS.length);q=n+10;q>=COLOR_GRADIENTS_STACKS.length&&(q-=COLOR_GRADIENTS_STACKS.length)};this.startFade=function(){w.visible=!0;w.alpha=1;createjs.Tween.get(w).to({alpha:0},MS_FADE_ANIM,createjs.Ease.cubicOut).call(function(){w.visible=
!1})};this.resetContainerStacks=function(){y.x=CANVAS_WIDTH_HALF;y.y=CANVAS_HEIGHT;y.regX=CANVAS_WIDTH_HALF;y.regY=CANVAS_HEIGHT;y.scaleX=y.scaleY=1;m=y.y};this.createStartStacks=function(){for(var a=[],b=0;b<NUM_OF_EDGES_FOR_STACK;b++)a.push(new CEdge(START_EDGES_POSITION[b].startX,START_EDGES_POSITION[b].startY,START_EDGES_POSITION[b].endX,START_EDGES_POSITION[b].endY));z=new CStack({x:CANVAS_WIDTH_HALF,y:CANVAS_HEIGHT_HALF+150,dir:NO_DIR},{line:COLOR_GRADIENTS_STACKS[n],plane:COLOR_GRADIENTS_STACKS[n],
width:LINES_WIDTH,depth:null},a,y);z.setID(0);x.push(z);this.nextColorGradient();v=new CStack({x:STACKS_START_POSITION[l].x,y:STACKS_START_POSITION[l].y-STACK_DEPTH_SIZE,dir:STACKS_START_POSITION[l].dir},{line:COLOR_GRADIENTS_STACKS[n],plane:COLOR_GRADIENTS_STACKS[n],width:LINES_WIDTH,depth:null},a,y);v.setID(1);a=z.getPos();a.y-=STACK_DEPTH_SIZE;v.setLimitPosition(this.getLimitPos(a));v.setPosition(v.getLimitPosition(3-l).x,v.getLimitPosition(3-l).y);this.nextColorGradient();x.push(v)};this.zoomOutContainerStacks=
function(){var a=1/(.06*k);1<a&&(a=1);var b=y.y+(x[Math.floor(x.length-1)].getPos().y-x[0].getPos().y);createjs.Tween.get(y).to({scaleX:a,scaleY:a,y:b},MS_TIME_ZOOM_OUT,createjs.Ease.quartOut)};this.gameOver=function(){h=STATE_FINISH;v.fallEffect();this.zoomOutContainerStacks();this.visibleAllStacks();k>s_iBestScore&&(s_iBestScore=k,saveItem("box_best_score",k));t.createWinPanel(k)};this.onMouseDown=function(){v.updateEdgesPosition();var a=s_oGame.intersectionPointsStacks(z,v);!1===a.result?h===STATE_PLAY&&
s_oGame.gameOver():(s_oGame.nextColorGradient(),s_oGame.moveContainerStack(),v.updateSize(),v.cacheStack(),s_oGame.changeDirStack(),s_oGame.createNewStack(v.getEdges(),a.point,a.cut),s_oGame.addScore(1),s_oGame.animPerfectText(a.cut),s_oGame.checkVisibleStack())};this.animPerfectText=function(a){a||t.animPerfectText()};this.nextColorGradient=function(){n++;q++;n===COLOR_GRADIENTS_STACKS.length&&(n=0);q===COLOR_GRADIENTS_STACKS.length&&(q=0);u.graphics.clear();u.graphics.beginFill(COLOR_GRADIENTS_STACKS[q]).drawRect(0,
0,CANVAS_WIDTH,CANVAS_HEIGHT).endFill();u.updateCache()};this.checkVisibleStack=function(){for(var a=p;a<x.length;a++)if(x[a].isVisible()&&x[a].getPosLocal().y>CANVAS_HEIGHT){x[a].setVisible(!1);p=a;break}};this.visibleAllStacks=function(){for(var a=0;a<x.length;a++)x[a].setVisible(!0)};this.addScore=function(a){k+=a;t.refreshScoreText(k);k>s_iBestScore&&t.refreshBestScore(k,!0)};this.intersectionPointsStacks=function(a,b){var f=1;if(b.getDirID()===LEFT_UP||b.getDirID()===RIGHT_DOWN)f=0;var c,d,e,
g,k;0===f?(c=a.getLeftDownAndRightUpEdges(),d=b.getLeftDownAndRightUpEdges(),e=b.getLeftUpAndRightDownEdges()):(c=a.getLeftUpAndRightDownEdges(),d=b.getLeftUpAndRightDownEdges(),e=b.getLeftDownAndRightUpEdges());g=this.checkIntersectionPoint(c[0],d[0]);k=this.checkIntersectionPoint(c[1],d[1]);if(0===k.result||1===k.result||0===g.result||1===g.result)return{result:!1};c=d[0].getPointA().getX()-g.vec1.getX();var h=d[1].getPointA().getX()-k.vec1.getX(),n=d[0].getPointA().getY()-g.vec1.getY(),l=d[1].getPointA().getY()-
k.vec1.getY(),w=d[0].getPointB().getX()-g.vec2.getX(),m=d[1].getPointB().getX()-k.vec2.getX();g=d[0].getPointB().getY()-g.vec2.getY();k=d[1].getPointB().getY()-k.vec2.getY();var p={x:0,y:0},x=!1,q,u,r=!1;0===f?0!==c&&0!==m?(p={x:c,y:n},Math.abs(c)>PERFECT_RANGE&&Math.abs(m)>PERFECT_RANGE&&(r=!0,q=e[1],u=new CEdge(e[1].getPointB().getX(),e[1].getPointB().getY(),e[1].getPointA().getX(),e[1].getPointA().getY(),e[1].getInfo()),this.newEdgesPosition({right:d[0],left:d[1],distance:e[1],point1:{x:c,y:n},
point2:{x:m,y:k}}),x=!0)):0!==w&&0!==h&&(p={x:h,y:l},Math.abs(w)>PERFECT_RANGE&&Math.abs(h)>PERFECT_RANGE&&(q=e[0],u=new CEdge(e[0].getPointB().getX(),e[0].getPointB().getY(),e[0].getPointA().getX(),e[0].getPointA().getY(),e[0].getInfo()),this.newEdgesPosition({right:d[1],left:d[0],distance:e[0],point1:{x:w,y:g},point2:{x:h,y:l}}),x=!0)):0!==c&&0!==m?(p={x:m,y:k},Math.abs(c)>PERFECT_RANGE&&Math.abs(m)>PERFECT_RANGE&&(q=e[0],u=new CEdge(e[0].getPointB().getX(),e[0].getPointB().getY(),e[0].getPointA().getX(),
e[0].getPointA().getY(),e[0].getInfo()),this.newEdgesPosition({right:d[0],left:d[1],distance:e[0],point1:{x:c,y:n},point2:{x:m,y:k}}),x=!0)):0!==w&&0!==h&&(r=!0,p={x:w,y:g},Math.abs(w)>PERFECT_RANGE&&Math.abs(h)>PERFECT_RANGE&&(u=new CEdge(e[1].getPointB().getX(),e[1].getPointB().getY(),e[1].getPointA().getX(),e[1].getPointA().getY(),e[1].getInfo()),q=e[1],this.newEdgesPosition({right:d[1],left:d[0],distance:e[1],point1:{x:w,y:g},point2:{x:h,y:l}}),x=!0));x&&this.cutStack(q,u,p,r);return{result:!0,
point:p,cut:x}};this.cutStack=function(a,b,f,c){var d=[];switch(v.getDirID()){case 0:case 3:c?(d.push(new CEdge(b.getPointA().getX(),b.getPointA().getY(),a.getPointB().getX(),a.getPointB().getY())),d.push(new CEdge(a.getPointB().getX(),a.getPointB().getY(),a.getPointA().getX(),a.getPointA().getY())),d.push(new CEdge(a.getPointA().getX(),a.getPointA().getY(),b.getPointB().getX(),b.getPointB().getY())),d.push(new CEdge(b.getPointB().getX(),b.getPointB().getY(),b.getPointA().getX(),b.getPointA().getY()))):
(d.push(new CEdge(a.getPointA().getX(),a.getPointA().getY(),b.getPointB().getX(),b.getPointB().getY())),d.push(new CEdge(b.getPointB().getX(),b.getPointB().getY(),b.getPointA().getX(),b.getPointA().getY())),d.push(new CEdge(b.getPointA().getX(),b.getPointA().getY(),a.getPointB().getX(),a.getPointB().getY())),d.push(new CEdge(a.getPointB().getX(),a.getPointB().getY(),a.getPointA().getX(),a.getPointA().getY())));break;case 1:case 2:c?(d.push(new CEdge(a.getPointB().getX(),a.getPointB().getY(),a.getPointA().getX(),
a.getPointA().getY())),d.push(new CEdge(a.getPointA().getX(),a.getPointA().getY(),b.getPointB().getX(),b.getPointB().getY())),d.push(new CEdge(b.getPointB().getX(),b.getPointB().getY(),b.getPointA().getX(),b.getPointA().getY())),d.push(new CEdge(b.getPointA().getX(),b.getPointA().getY(),a.getPointB().getX(),a.getPointB().getY()))):(d.push(new CEdge(b.getPointB().getX(),b.getPointB().getY(),b.getPointA().getX(),b.getPointA().getY())),d.push(new CEdge(b.getPointA().getX(),b.getPointA().getY(),a.getPointB().getX(),
a.getPointB().getY())),d.push(new CEdge(a.getPointB().getX(),a.getPointB().getY(),a.getPointA().getX(),a.getPointA().getY())),d.push(new CEdge(a.getPointA().getX(),a.getPointA().getY(),b.getPointB().getX(),b.getPointB().getY())))}a={x:v.getPos().x,y:v.getPos().y,dir:NO_DIR};if(SHOW_CUT_EDGES)for(b=0;b<d.length;b++){c=new createjs.Shape;c.graphics.beginStroke(DEFAULT_COLOR[b]);c.graphics.setStrokeStyle(LINES_WIDTH);c.graphics.moveTo(d[b].getPointA().getX(),d[b].getPointA().getY());c.graphics.lineTo(d[b].getPointB().getX(),
d[b].getPointB().getY());var e=new createjs.Shape;e.graphics.beginFill("#fff").drawCircle(d[b].getPointA().getX(),d[b].getPointA().getY(),10);var g=new createjs.Shape;g.graphics.beginFill("#000").drawCircle(d[b].getPointB().getX(),d[b].getPointB().getY(),10);y.addChild(c,g,e)}d=this.createStack(d,{x:0,y:0},a,v.getColor());0>f.x&&0>f.y?d.setChildIndex(0):0<f.x&&0>f.y&&d.setChildIndex(0);d.fallEffect()};this.newEdgesPosition=function(a){a.right.set(a.right.getPointA().getX()-a.point1.x,a.right.getPointA().getY()-
a.point1.y,a.right.getPointB().getX(),a.right.getPointB().getY());a.left.set(a.left.getPointA().getX(),a.left.getPointA().getY(),a.left.getPointB().getX()-a.point2.x,a.left.getPointB().getY()-a.point2.y);a.distance.set(a.left.getPointB().getX(),a.left.getPointB().getY(),a.right.getPointA().getX(),a.right.getPointA().getY())};this.checkIntersectionPoint=function(a,b){var d=new CVector2(0,0),f=new CVector2(0,0),c=new CEdge(a.getPointA().getX()+0,a.getPointA().getY()+0,a.getPointB().getX()+0,a.getPointB().getY()+
0),c=intersect2D_Segments(c,b,d,f);return{vec1:d,vec2:f,result:c}};this.createNewStack=function(a,d,f){f?(playSound("cut",1,0),f={x:v.getPos().x-d.x,y:v.getPos().y-STACK_DEPTH_SIZE-d.y,dir:STACKS_START_POSITION[l].dir}):(playSound("perfect",1,0),v.perfectPosition(),v.setPosition(z.getPos().x-c,z.getPos().y-b-STACK_DEPTH_SIZE),v.updateEdgesPosition(),f={x:v.getPos().x+c-d.x,y:v.getPos().y-STACK_DEPTH_SIZE+b-d.y,dir:STACKS_START_POSITION[l].dir});c=d.x;b=d.y;a=this.createStack(a,d,f,{line:COLOR_GRADIENTS_STACKS[n],
plane:COLOR_GRADIENTS_STACKS[n],width:LINES_WIDTH,depth:null});a.setLimitPosition(this.getLimitPos(f));a.setPosition(a.getLimitPosition(3-l).x,a.getLimitPosition(3-l).y);x.push(a);z=v;v=a};this.createStack=function(a,b,d,f){for(var c=v.getPos(),e=[],g=0;g<a.length;g++)e[g]=new CEdge(a[g].getPointA().getX()-c.x+b.x,a[g].getPointA().getY()-c.y+b.y,a[g].getPointB().getX()-c.x+b.x,a[g].getPointB().getY()-c.y+b.y,START_EDGES_POSITION[g].type);return new CStack(d,f,e,y)};this.changeDirStack=function(){1===
l?l=0:l++};this.moveContainerStack=function(){m+=STACK_DEPTH_SIZE;createjs.Tween.get(y,{override:!0}).to({y:m},MS_SCROLL_CONTAINER_STACK,createjs.Ease.cubicOut).call(function(){},null,this)};this.getLimitPos=function(a){for(var b=[],d=0;d<STACKS_LIMIT_POSITION.length;d++)b.push({x:a.x+DIRECTION_STACKS[d].x*STACKS_DISTANCE_OFFSET,y:a.y+DIRECTION_STACKS[d].y*STACKS_DISTANCE_OFFSET});return b};this.unload=function(){e=!1;t.unload();s_oStage.removeAllChildren();createjs.Tween.removeAllTweens()};this.onExit=
function(){$(s_oMain).trigger("end_session");$(s_oMain).trigger("end_level",1);var a=this;w.visible=!0;createjs.Tween.get(w,{override:!0}).to({alpha:1},MS_FADE_ANIM,createjs.Ease.cubicOut).call(function(){$(s_oMain).trigger("show_interlevel_ad");a.unload();setVolume(s_oSoundTrack,1);s_oMain.gotoMenu()})};this._onStart=function(){h=STATE_PLAY;setVolume(s_oSoundTrack,.3)};this.restartGame=function(){w.visible=!0;createjs.Tween.get(w,{ignoreGlobalPause:!0,override:!0}).to({alpha:1},MS_FADE_ANIM,createjs.Ease.cubicOut).call(function(){for(var a=
0;a<x.length;a++)x[a].unload();x=[];s_oGame.resetContainerStacks();z=null;k=b=c=0;t.refreshScoreText(k);s_oGame.restartColorGrandients();s_oGame.createStartStacks();s_oGame.startFade();t.refreshBestScore(s_iBestScore,!1);h=STATE_PLAY})};this.unpause=function(a){e=a};this._onEnd=function(){w.visible=!0;createjs.Tween.get(w,{ignoreGlobalPause:!0}).to({alpha:1},MS_FADE_ANIM,createjs.Ease.cubicOut).call(function(){s_oGame.unload();$(s_oMain).trigger("end_level",1);$(s_oMain).trigger("end_session");setVolume(s_oSoundTrack,
1);s_oMain.gotoMenu()})};this._updatePlay=function(){e&&v.update(STACK_VELOCITY)};this.update=function(){switch(h){case STATE_PLAY:this._updatePlay()}};s_oGame=this;STACK_VELOCITY=a.stack_velocity;NUM_LEVEL_FOR_ADS=a.num_levels_for_ads;ENABLE_FULLSCREEN=a.fullscreen;this._init()}var s_oGame;
function CInterface(a,c){var b,d,f,e,g,k,h,l,m,n,q,p,t,u,r,w,y,z,v=null,A=null;this._init=function(){var a=s_oSpriteLibrary.getSprite("but_exit");f=CANVAS_WIDTH-a.height/2-15;e=a.height/2+15;h=new CGfxButton(f,e,a,s_oStage);h.addEventListener(ON_MOUSE_UP,this._onExit,this);a=s_oSpriteLibrary.getSprite("but_restart_small");k={x:f-a.height-15,y:e};l=new CGfxButton(k.x,k.y,a,s_oStage);l.addEventListener(ON_MOUSE_UP,this._onRestart,this);!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(a=s_oSpriteLibrary.getSprite("audio_icon"),
g={x:k.x-a.height-15,y:e},p=new CToggle(g.x,g.y,a,s_bAudioActive,s_oStage),p.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this)):g=k;var a=window.document,c=a.documentElement;v=c.requestFullscreen||c.mozRequestFullScreen||c.webkitRequestFullScreen||c.msRequestFullscreen;A=a.exitFullscreen||a.mozCancelFullScreen||a.webkitExitFullscreen||a.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(v=!1);v&&!1===inIframe()&&(a=s_oSpriteLibrary.getSprite("but_fullscreen"),b=g.x-a.width/2-15,d=e,z=new CToggle(b,d,
a,s_oStage),z.addEventListener(ON_MOUSE_UP,this._onFullscreen,this));r=new CScoreBoard(s_oStage);w=new CTextPerfect(s_oStage);this.createButStart();this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.createButStart=function(){n=new createjs.Shape;n.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);n.on("click",function(){});s_oStage.addChild(n);var a=s_oSpriteLibrary.getSprite("but_start");m=new CGfxButton(CANVAS_WIDTH_HALF,CANVAS_HEIGHT_HALF,a,s_oStage);m.addEventListener(ON_MOUSE_UP,
this._onMouseUpStart,this);m.pulseAnimation()};this.refreshButtonPos=function(a,c){h.setPosition(f-a,c+e);l.setPosition(k.x-a,c+k.y);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||p.setPosition(g.x-a,c+g.y);var n=r.getStartPosScore();r.setPosScore(n.x+a,n.y+c);v&&!1===inIframe()&&z.setPosition(b-a,d+c);w.updatePoints(a,c)};this._onMouseUpStart=function(){n.removeAllEventListeners();s_oStage.removeChild(n);s_oGame._onStart();m.unload();m=null};this.unload=function(){h.unload();h=null;l.unload();l=null;
if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)p.unload(),p=null;v&&!1===inIframe()&&z.unload();s_oInterface=null};this.createHelpPanel=function(){q=new CHelpPanel(0,0,s_oSpriteLibrary.getSprite("msg_box"))};this.createLosePanel=function(a,b){t=new CLosePanel(s_oSpriteLibrary.getSprite("bg_congratulations"));t.show(a,b,_iPlayerTeam,_iOpponentTeam)};this.createWinPanel=function(a){u=new CWinPanel(s_oSpriteLibrary.getSprite("msg_box"));u.show(a)};this.unloadHelpPanel=function(){q&&(q.unload(),q=null)};
this.createPauseInterface=function(){y=new CPause};this.refreshScoreText=function(a){r.refreshTextScore(a)};this.refreshBestScore=function(a,b){r.refreshTextBestScore(a,b)};this.animPerfectText=function(){w.animText()};this.refreshLevelText=function(a){(void 0).refreshTextLevel(a)};this.unloadPause=function(){y.unload();y=null};this.subEffect=function(a){r.effectSubtractScore(a)};this._onFullscreen=function(){s_bFullscreen?(A.call(window.document),s_bFullscreen=!1):(v.call(window.document.documentElement),
s_bFullscreen=!0);sizeHandler()};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onExit=function(){(new CAreYouSurePanel(s_oStage)).show()};this.blockCommand=function(a){s_bMobile&&(void 0).block(a)};this._onRestart=function(){s_oGame.restartGame()};s_oInterface=this;this._init(a,c);return this}var s_oInterface=null;
function CHelpPanel(a,c,b){var d,f,e,g,k,h,l,m,n,q,p,t=!1;this._init=function(a,b,d){e=createBitmap(d);e.x=.5*CANVAS_WIDTH;e.y=.5*CANVAS_HEIGHT;e.regX=.5*d.width;e.regY=.5*d.height;g=new createjs.Container;g.x=a;g.y=b;h=new createjs.Shape;h.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);h.alpha=.5;g.addChild(h);g.addChild(e);s_oStage.addChild(g);g.on("pressup",function(){s_oHelpPanel._onExitHelp()},null,!0);k=new createjs.Container;k.alpha=0;this.page1(k);s_bMobile||(h.cursor=
"pointer")};this.page1=function(a){var b;b=new createjs.Text(TEXT_CONTROLS,"32px "+FONT_GAME,"#ff6000");b.x=.5*CANVAS_WIDTH;b.y=.5*CANVAS_HEIGHT-200;b.textAlign="center";b.outline=5;a.addChild(b);var c;c=new createjs.Text(TEXT_CONTROLS,"32px "+FONT_GAME,TEXT_COLOR);c.x=.5*CANVAS_WIDTH;c.y=b.y;c.textAlign="center";a.addChild(c);d=CANVAS_WIDTH_HALF;f=340;m=new CArrow(d,f,a);m.animateMask(1E3);b=s_oSpriteLibrary.getSprite("ball");c=s_bMobile?s_oSpriteLibrary.getSprite("help_touch"):s_oSpriteLibrary.getSprite("help_mouse");
q=createBitmap(c);q.x=d-130;q.y=f-10;q.regX=.5*c.width;q.regY=.5*c.height;a.addChild(q);new CBall(d,f,null,b,a);this.animateInputPower(1E3);n=new CArrow(d,f+160,a);n.animateRotation(1E3);n.mask(100);p=createBitmap(c);p.x=d-150;p.y=f+160;p.regX=.5*c.width;p.regY=.5*c.height;a.addChild(p);new CBall(d,f+160,null,b,a);this.animateInputRotate(1E3);createjs.Tween.get(a).to({alpha:1},300,createjs.Ease.cubicOut);b=s_oSpriteLibrary.getSprite("but_continue");l=new CGfxButton(.5*CANVAS_WIDTH+310,.5*CANVAS_HEIGHT+
145,b,a);l.addEventListener(ON_MOUSE_UP,this._onExitHelp,this);l.pulseAnimation();s_oStage.addChild(a)};this.animateInputPower=function(a){createjs.Tween.get(q).to({x:d-230},a,createjs.Ease.cubicInOut).call(function(){createjs.Tween.get(q).to({x:d-130},a,createjs.Ease.cubicInOut).call(function(){s_oHelpPanel.animateInputPower(a)})})};this.animateInputRotate=function(a){createjs.Tween.get(p).to({y:f+60},a,createjs.Ease.cubicInOut).call(function(){createjs.Tween.get(p).to({y:f+180},a,createjs.Ease.cubicInOut).call(function(){s_oHelpPanel.animateInputRotate(a)})})};
this.unload=function(){s_oStage.removeChild(g,k);s_oHelpPanel=null;g.off("pressup",function(){s_oHelpPanel._onExitHelp()},null,!0);l.unload();l=null;createjs.Tween.removeAllTweens()};this._onExitHelp=function(){if(!t){t=!0;playSound("click",1,0);var a=this;createjs.Tween.get(k).to({alpha:0},300,createjs.Ease.cubicOut).call(function(){a.unload();s_oGame._onExitHelp()})}};s_oHelpPanel=this;this._init(a,c,b)}var s_oHelpPanel=null;
function CWinPanel(a,c){var b,d,f,e,g,k,h,l,m,n,q;this._init=function(a){l=new createjs.Container;l.alpha=0;l.visible=!1;var c=new createjs.Shape;c.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);c.alpha=.5;l.addChild(c);b=createBitmap(a);b.x=CANVAS_WIDTH_HALF;b.y=CANVAS_HEIGHT_HALF;b.regX=.5*a.width;b.regY=.5*a.height;l.addChild(b);d=new createjs.Text("","100px "+FONT_GAME,TEXT_COLOR_STROKE);d.x=CANVAS_WIDTH/2;d.y=500;d.textAlign="center";d.outline=5;l.addChild(d);f=new createjs.Text("",
"100px "+FONT_GAME,TEXT_COLOR);f.x=CANVAS_WIDTH/2;f.y=d.y;f.textAlign="center";l.addChild(f);e=new createjs.Text("","50px "+FONT_GAME,TEXT_COLOR_STROKE);e.x=CANVAS_WIDTH/2;e.y=CANVAS_HEIGHT_HALF-50;e.textAlign="center";e.outline=5;l.addChild(e);g=new createjs.Text("","50px "+FONT_GAME,TEXT_COLOR);g.x=CANVAS_WIDTH/2;g.y=e.y;g.textAlign="center";l.addChild(g);k=new createjs.Text("","50px "+FONT_GAME,TEXT_COLOR_STROKE);k.x=CANVAS_WIDTH/2;k.y=CANVAS_HEIGHT_HALF+50;k.textAlign="center";k.outline=5;l.addChild(k);
h=new createjs.Text("","50px "+FONT_GAME,TEXT_COLOR);h.x=CANVAS_WIDTH/2;h.y=k.y;h.textAlign="center";l.addChild(h);a=s_oSpriteLibrary.getSprite("but_restart");n=new CGfxButton(.5*CANVAS_WIDTH+290,.5*CANVAS_HEIGHT+130,a,l);n.pulseAnimation();n.addEventListener(ON_MOUSE_DOWN,this._onRestart,this);a=s_oSpriteLibrary.getSprite("but_home");m=new CGfxButton(.5*CANVAS_WIDTH-290,.5*CANVAS_HEIGHT+130,a,l);m.addEventListener(ON_MOUSE_DOWN,this._onExit,this);q=new createjs.Container;l.addChild(q);l.on("click",
function(){});s_oStage.addChild(l)};this.unload=function(){l.removeAllEventListeners();s_oStage.removeChild(l);m&&(m.unload(),m=null);n&&(n.unload(),n=null)};this.show=function(a){d.text=TEXT_GAMEOVER;f.text=TEXT_GAMEOVER;e.text=TEXT_SCORE+": "+a;g.text=TEXT_SCORE+": "+a;k.text=TEXT_BEST_SCORE+": "+s_iBestScore;h.text=TEXT_BEST_SCORE+": "+s_iBestScore;l.visible=!0;createjs.Tween.get(l).wait(MS_WAIT_SHOW_GAME_OVER_PANEL).to({alpha:1},1250,createjs.Ease.cubicOut).call(function(){s_oAdsLevel===NUM_LEVEL_FOR_ADS?
($(s_oMain).trigger("show_interlevel_ad"),s_oAdsLevel=1):s_oAdsLevel++});$(s_oMain).trigger("save_score",a);$(s_oMain).trigger("share_event",a)};this._onContinue=function(){var a=this;createjs.Tween.get(l,{override:!0}).to({alpha:0},750,createjs.Ease.cubicOut).call(function(){a.unload()});_oButContinue.block(!0);m.block(!0);s_oGame.onContinue()};this._onRestart=function(){n.block(!0);this.unload();s_oGame.restartGame()};this._onExit=function(){this.unload();s_oGame.onExit()};this._init(a,c);return this}
var _0x5059="_init;addChild;drawRect;black;beginFill;graphics;alpha;msg_box;getSprite;x;y;regX;width;regY;height;#0f0f0f;click;on;cursor;pointer;secret;but_exit;unload;addEventListener;40px ;textAlign;center;textBaseline;alphabetic;outline;logo_ctl;http://www.fz222.com/;50px ;CREATED BY GENNARO PALLADINO EX FZ222 DEVELOPER;lineWidth;getBounds;removeChild;call;cubicOut;Ease;to;wait;bounceOut;get;Tween;off;_onLogoButRelease;http://www.fz222.com/;_blank;open".split(";");
function CCreditsPanel(){var a,c,b,d,f,e,g,k,h,l,m=0;this[_0x5059[0]]=function(){l=new createjs.Container;s_oStage[_0x5059[1]](l);var n=new createjs.Shape;n[_0x5059[5]][_0x5059[4]](_0x5059[3])[_0x5059[2]](0,0,CANVAS_WIDTH,CANVAS_HEIGHT);n[_0x5059[6]]=.6;l[_0x5059[1]](n);n=s_oSpriteLibrary[_0x5059[8]](_0x5059[7]);a=createBitmap(n);a[_0x5059[9]]=CANVAS_WIDTH_HALF;a[_0x5059[10]]=CANVAS_HEIGHT_HALF;a[_0x5059[11]]=.5*n[_0x5059[12]];a[_0x5059[13]]=.5*n[_0x5059[14]];l[_0x5059[1]](a);e=new createjs.Shape;
e[_0x5059[5]][_0x5059[4]](_0x5059[15])[_0x5059[2]](0,0,CANVAS_WIDTH,CANVAS_HEIGHT);e[_0x5059[6]]=.01;e[_0x5059[17]](_0x5059[16],this._onLogoButRelease);e[_0x5059[18]]=_0x5059[19];l[_0x5059[1]](e);n=new createjs.Shape;n[_0x5059[5]][_0x5059[4]](_0x5059[15])[_0x5059[2]](CANVAS_WIDTH-2*EDGEBOARD_X,CANVAS_HEIGHT-2*EDGEBOARD_Y,2*EDGEBOARD_X,2*EDGEBOARD_Y);n[_0x5059[6]]=.01;n[_0x5059[17]](_0x5059[16],this[_0x5059[20]]);n[_0x5059[18]]=_0x5059[19];l[_0x5059[1]](n);n=s_oSpriteLibrary[_0x5059[8]](_0x5059[21]);
h={x:.5*CANVAS_WIDTH+330,y:510};b=new CGfxButton(h[_0x5059[9]],h[_0x5059[10]],n,l);b[_0x5059[23]](ON_MOUSE_UP,this[_0x5059[22]],this);f=new createjs.Text(TEXT_CREDITS_DEVELOPED,_0x5059[24]+FONT_GAME,TEXT_COLOR_STROKE);f[_0x5059[25]]=_0x5059[26];f[_0x5059[27]]=_0x5059[28];f[_0x5059[9]]=CANVAS_WIDTH/2;f[_0x5059[10]]=560;f[_0x5059[29]]=1;l[_0x5059[1]](f);d=new createjs.Text(TEXT_CREDITS_DEVELOPED,_0x5059[24]+FONT_GAME,TEXT_COLOR);d[_0x5059[25]]=_0x5059[26];d[_0x5059[27]]=_0x5059[28];d[_0x5059[9]]=f[_0x5059[9]];
d[_0x5059[10]]=f[_0x5059[10]];l[_0x5059[1]](d);n=s_oSpriteLibrary[_0x5059[8]](_0x5059[30]);c=createBitmap(n);c[_0x5059[11]]=n[_0x5059[12]]/2;c[_0x5059[13]]=n[_0x5059[14]]/2;c[_0x5059[9]]=CANVAS_WIDTH/2;c[_0x5059[10]]=f[_0x5059[10]]+100;l[_0x5059[1]](c);k=new createjs.Text(_0x5059[31],_0x5059[32]+FONT_GAME,TEXT_COLOR_STROKE);k[_0x5059[25]]=_0x5059[26];k[_0x5059[27]]=_0x5059[28];k[_0x5059[9]]=CANVAS_WIDTH/2;k[_0x5059[10]]=f[_0x5059[10]]+240;k[_0x5059[29]]=1;l[_0x5059[1]](k);g=new createjs.Text(_0x5059[31],
_0x5059[32]+FONT_GAME,TEXT_COLOR);g[_0x5059[25]]=_0x5059[26];g[_0x5059[27]]=_0x5059[28];g[_0x5059[9]]=k[_0x5059[9]];g[_0x5059[10]]=k[_0x5059[10]];l[_0x5059[1]](g)};this[_0x5059[20]]=function(){if(5===m){var a=new createjs.Text(_0x5059[33],_0x5059[24]+FONT_GAME,TEXT_COLOR);a[_0x5059[25]]=_0x5059[26];a[_0x5059[27]]=_0x5059[28];a[_0x5059[34]]=500;var b=new createjs.Text(_0x5059[33],_0x5059[24]+FONT_GAME,TEXT_COLOR_STROKE);b[_0x5059[25]]=_0x5059[26];b[_0x5059[27]]=_0x5059[28];b[_0x5059[34]]=500;b[_0x5059[29]]=
1;var c=new createjs.Container;c[_0x5059[1]](a);c[_0x5059[1]](b);c[_0x5059[9]]=CANVAS_WIDTH_HALF;c[_0x5059[10]]=-a[_0x5059[35]]()[_0x5059[14]];l[_0x5059[1]](c);createjs[_0x5059[44]][_0x5059[43]](c)[_0x5059[40]]({y:CANVAS_HEIGHT_HALF+300},1E3,createjs[_0x5059[39]][_0x5059[42]])[_0x5059[41]](3E3)[_0x5059[40]]({alpha:0},1E3,createjs[_0x5059[39]][_0x5059[38]])[_0x5059[37]](function(){l[_0x5059[36]](a);m=0})}m++};this[_0x5059[22]]=function(){e[_0x5059[45]](_0x5059[16],this._onLogoButRelease);b[_0x5059[22]]();
b=null;s_oStage[_0x5059[36]](l)};this[_0x5059[46]]=function(){window[_0x5059[49]](_0x5059[47],_0x5059[48])};this._init()}
function CPause(){var a;this._init=function(){var c=new createjs.Container;c.alpha=0;a=new createjs.Shape;a.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);a.alpha=.5;var b=new createjs.Shape;b.graphics.beginFill("#0f0f0f").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);a.hitArea=b;a.on("click",function(){});c.addChild(a);b=new createjs.Text(TEXT_PAUSE,"50px "+FONT_GAME,"#000000");b.x=.5*CANVAS_WIDTH;b.y=.5*CANVAS_HEIGHT-130;b.textAlign="center";b.outline=5;c.addChild(b);var d=new createjs.Text(TEXT_PAUSE,
"50px "+FONT_GAME,TEXT_COLOR);d.x=b.x;d.y=b.y;d.textAlign="center";c.addChild(d);b=s_oSpriteLibrary.getSprite("but_continue");(new CGfxButton(.5*CANVAS_WIDTH,.5*CANVAS_HEIGHT+70,b,c)).addEventListenerWithParams(ON_MOUSE_UP,this._onLeavePause,this,c);s_oStage.addChild(c);createjs.Tween.get(c).to({alpha:1},300,createjs.quartOut)};this.unload=function(){a.off("click",function(){});s_oStage.removeChild(void 0)};this._onLeavePause=function(a){createjs.Tween.get(a).to({alpha:0},300,createjs.quartIn).call(function(){s_oInterface.unloadPause();
s_oGame.unpause(!0)})};this._init();return this}
function CAreYouSurePanel(a){var c,b,d,f,e,g;this._init=function(){e=new createjs.Container;e.alpha=0;g.addChild(e);var a=new createjs.Shape;a.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);a.alpha=.5;e.addChild(a);var a=s_oSpriteLibrary.getSprite("msg_box"),h=createBitmap(a);h.x=CANVAS_WIDTH_HALF;h.y=CANVAS_HEIGHT_HALF;h.regX=.5*a.width;h.regY=.5*a.height;e.addChild(h);c=new createjs.Text(TEXT_ARE_SURE,"80px "+FONT_GAME,TEXT_COLOR_STROKE);c.x=CANVAS_WIDTH/2;c.y=550;c.textAlign=
"center";c.textBaseline="middle";c.outline=1;e.addChild(c);b=new createjs.Text(c.text,"80px "+FONT_GAME,TEXT_COLOR);b.x=c.x;b.y=c.y;b.textAlign="center";b.textBaseline="middle";e.addChild(b);e.on("click",function(){});d=new CGfxButton(CANVAS_WIDTH/2+280,CANVAS_HEIGHT_HALF+120,s_oSpriteLibrary.getSprite("but_yes"),e);d.addEventListener(ON_MOUSE_UP,this._onButYes,this);f=new CGfxButton(CANVAS_WIDTH/2-280,CANVAS_HEIGHT_HALF+120,s_oSpriteLibrary.getSprite("but_no"),e);f.addEventListener(ON_MOUSE_UP,this._onButNo,
this);f.pulseAnimation()};this.show=function(){s_oGame.unpause(!1);createjs.Tween.get(e,{ignoreGlobalPause:!0}).to({alpha:1},500,createjs.Ease.cubicOut)};this._onButYes=function(){s_oGame.unpause(!0);this.unload();s_oGame.onExit()};this._onButNo=function(){var a=this;createjs.Tween.get(e,{ignoreGlobalPause:!0}).to({alpha:0},500,createjs.Ease.cubicOut).call(function(){s_oGame.unpause(!0);a.unload()})};this.unload=function(){d.unload();d=null;f.unload();f=null;e.removeAllEventListeners();s_oStage.removeChild(e)};
g=a;this._init()}
function CVector2(a,c){var b,d;this._init=function(a,c){b=a;d=c};this.add=function(a,c){b+=a;d+=c};this.addV=function(a){b+=a.getX();d+=a.getY()};this.scalarDivision=function(a){b/=a;d/=a};this.subtract=function(a){b-=a.getX();d-=a.getY()};this.scalarProduct=function(a){b*=a;d*=a};this.invert=function(){b*=-1;d*=-1};this.dotProduct=function(a){return b*a.getX()+d*a.getY()};this.set=function(a,c){b=a;d=c};this.setV=function(a){b=a.getX();d=a.getY()};this.length=function(){return Math.sqrt(b*b+d*d)};
this.length2=function(){return b*b+d*d};this.normalize=function(){var a=this.length();0<a&&(b/=a,d/=a)};this.angleBetweenVectors=function(a){a=Math.acos(this.dotProduct(a)/(this.length()*a.length()));return!0===isNaN(a)?0:a};this.getNormalize=function(a){this.length();a.set(b,d);a.normalize()};this.rot90CCW=function(){var a=b;b=-d;d=a};this.rot90CW=function(){var a=b;b=d;d=-a};this.getRotCCW=function(a){a.set(b,d);a.rot90CCW()};this.getRotCW=function(a){a.set(b,d);a.rot90CW()};this.ceil=function(){b=
Math.ceil(b);d=Math.ceil(d)};this.round=function(){b=Math.round(b);d=Math.round(d)};this.toString=function(){return"Vector2: "+b+", "+d};this.print=function(){trace("Vector2: "+b+", "+d+"")};this.getX=function(){return b};this.getY=function(){return d};this.rotate=function(a){var c=b,g=d;b=c*Math.cos(a)+g*Math.sin(a);d=c*-Math.sin(a)+g*Math.cos(a)};this._init(a,c)}
function CEdge(a,c,b,d,f){var e=null,g=null,k=null,h=null,l=null,m=null;this._init=function(a,b,c,d,e){this.set(a,b,c,d);m=e};this.destroy=function(){l=h=k=g=e=null};this.render=function(a){a.moveTo(e.x,e.y);a.lineTo(g.x,g.y)};this.toString=function(a){trace(a+" "+e.x+" "+e.y+" "+g.x+" "+g.y)};this.add=function(a){e.addV(a);g.addV(a)};this.set=function(a,b,c,d){e=new CVector2;g=new CVector2;e.set(a,b);g.set(c,d);this.calculateNormal();this.calculateCenter()};this.scale=function(a){e.scalarProduct(a);
g.scalarProduct(a);this.calculateNormal();this.calculateCenter()};this.calculateNormal=function(){l=null;l=new CVector2;l.setV(g);l.subtract(e);l.rot90CCW();l.normalize()};this.calculateCenter=function(){k=null;k=centerBetweenPointsV2(e,g);h=new CVector2;h.setV(l);h.scalarProduct(5);h.addV(k)};this.getPointA=function(){return e};this.m_pCenter=function(){return k};this.getPointB=function(){return g};this.getNormal=function(){return l};this.getInfo=function(){return f};this.toString=function(){return"A: "+
e.toString()+" B: "+g.toString()+" oInfo: "+m};this.renderNormal=function(a){a.moveTo(k.x,k.y);a.lineTo(h.x,h.y)};this._init(a,c,b,d,f);return this}
function CScoreBoard(a){var c,b,d,f,e,g,k,h,l,m;this._init=function(){h=new createjs.Container;l=new createjs.Container;l.x=-360;l.y=120;c={x:.5*CANVAS_WIDTH,y:61};k=new createjs.Container;k.x=c.x;k.y=c.y;a.addChild(k);k.addChild(l,h);f=new createjs.Text("999","40px "+FONT_GAME,TEXT_COLOR_STROKE);f.textAlign="center";f.textBaseline="middle";f.x=-7;f.outline=3;h.addChild(f);d=new createjs.Text("999","40px "+FONT_GAME,TEXT_COLOR);d.textAlign="center";d.textBaseline="middle";d.x=f.x;h.addChild(d);var n=
s_oSpriteLibrary.getSprite("bg_score"),q=createBitmap(n);q.regX=.5*n.width;q.regY=.5*n.height;h.addChild(q);h.x=-360;g=new createjs.Text("25","40px "+FONT_GAME,TEXT_COLOR_STROKE);g.textAlign="center";g.textBaseline="middle";g.outline=3;g.x=-5;l.addChild(g);e=new createjs.Text("25","40px "+FONT_GAME,TEXT_COLOR);e.textAlign="center";e.textBaseline="middle";e.x=g.x;l.addChild(e);b={x:l.x,y:0};n=this.createStar();l.addChild(n);m=this.createStar();m.visible=!1;m.alpha=0;l.addChild(m)};this.createStar=
function(){var a=s_oSpriteLibrary.getSprite("bg_bestscore"),a=new createjs.SpriteSheet({images:[a],frames:{width:a.width/2,height:a.height,regX:a.width/2/2,regY:a.height/2},animations:{normal:[0],active:[1]}}),a=createSprite(a,"normal",a.width/2/2,a.height/2,a.width/2,a.height);a.y=-5;a.x=5;return a};this.getStartPosScore=function(){return c};this.getStartPosBestScore=function(){return b};this.setBestScorePos=function(a,b){l.x=a;l.y=b};this.setPosScore=function(a,b){k.x=a;k.y=b};this.refreshTextBestScore=
function(a,b){e.text=a;g.text=a;b&&(m.visible=!0,createjs.Tween.get(m,{override:!0}).to({alpha:1},250,createjs.Ease.cubicOut).to({alpha:0},250,createjs.Ease.cubicIn).set({visible:!1}))};this.refreshTextScore=function(a){d.text=a;f.text=a};this._init();return this}
function CStack(a,c,b,d){var f,e,g,k,h,l,m=0,n,q,p,t,u,r;this._init=function(a,b,c){p=new createjs.Container;d.addChild(p);t=new createjs.Shape;u=new createjs.Shape;r=b;m=a.dir;l=new CVector2(DIRECTION_STACKS[a.dir].x,DIRECTION_STACKS[a.dir].y);h=[];this.setPosition(a.x,a.y);this.setEdges(c,{x:p.x,y:p.y});this.updateSize();p.addChild(t);p.addChild(u)};this.setLimitPosition=function(a){for(var b=0;b<a.length;b++)h.push(a[b])};this.getLimitPosition=function(a){return h[a]};this.getAllLimitPosition=
function(){return h};this.getLeftDownAndRightUpEdges=function(){return e};this.getLeftUpAndRightDownEdges=function(){return g};this.setDir=function(a){l.set(a.x,a.y)};this.getDir=function(){return l};this.isVisible=function(){return p.visible};this.setVisible=function(a){p.visible=a};this.getPosLocal=function(){return d.localToGlobal(p.x,p.y)};this.getDirID=function(){return m};this.getID=function(){return n};this.setID=function(a){n=a};this.cacheStack=function(){};this.updateCache=function(){};this.updateSize=
function(){this.createGraph(f,r);this.createDepthEdge();this.updateDepthEffect(k,r,!0)};this.createDepthEdge=function(){k=[];k.push({x:f[1].getPointA().getX(),y:f[1].getPointA().getY()});k.push({x:f[1].getPointB().getX(),y:f[1].getPointB().getY()});k.push({x:f[2].getPointB().getX(),y:f[2].getPointB().getY()});k.push({x:f[2].getPointB().getX(),y:f[2].getPointB().getY()+STACK_DEPTH_SIZE});k.push({x:f[1].getPointB().getX(),y:f[1].getPointB().getY()+STACK_DEPTH_SIZE});k.push({x:f[1].getPointA().getX(),
y:f[1].getPointA().getY()+STACK_DEPTH_SIZE})};this.updateDepthEffect=function(a,b,c){c&&(r.depth=colorLuminance(r.plane,DEPTH_LUMINANCE));u.graphics.clear();SHOW_EDGES&&u.graphics.beginStroke(b.depth);SHOW_FILL&&u.graphics.beginFill(b.depth);u.graphics.setStrokeStyle(r.width);for(b=0;b<a.length;b++)u.graphics.lineTo(a[b].x,a[b].y);u.graphics.closePath();u.x=-p.x;u.y=-p.y};this.perfectPosition=function(){var a=hexToRgb(r.plane),b=hexToRgb(colorLuminance(r.plane,.5)),c=this;new colorLerpShape(t,{r:a.r,
g:a.g,b:a.b,lerp:0},{r:b.r,g:b.g,b:b.b,lerp:1},0,MS_TIME_PERFECT_HIT,this.createGraph,createjs.Ease.cubicOut,f,"plane",function(){new colorLerpShape(t,{r:b.r,g:b.g,b:b.b,lerp:0},{r:a.r,g:a.g,b:a.b,lerp:1},0,MS_TIME_PERFECT_HIT,c.createGraph,createjs.Ease.cubicOut,f,"plane",null)});var d=hexToRgb(r.depth),e=hexToRgb(colorLuminance(r.depth,.5));new colorLerpShape(u,{r:d.r,g:d.g,b:d.b,lerp:0},{r:e.r,g:e.g,b:e.b,lerp:1},0,MS_TIME_PERFECT_HIT,this.updateDepthEffect,createjs.Ease.cubicOut,k,"depth",function(){new colorLerpShape(u,
{r:e.r,g:e.g,b:e.b,lerp:0},{r:d.r,g:d.g,b:d.b,lerp:1},0,MS_TIME_PERFECT_HIT,c.updateDepthEffect,createjs.Ease.cubicOut,k,"depth",null)})};this.updateEdgesPosition=function(){for(var a=0;a<f.length;a++)f[a].set(p.x+q[a].getPointA().getX(),p.y+q[a].getPointA().getY(),p.x+q[a].getPointB().getX(),p.y+q[a].getPointB().getY())};this.createGraph=function(a,b){t.graphics.clear();SHOW_EDGES&&t.graphics.beginStroke(b.plane);SHOW_FILL&&t.graphics.beginFill(b.plane);t.graphics.setStrokeStyle(r.width);for(var c=
0;c<a.length;c++)t.graphics.lineTo(a[c].getPointA().getX(),a[c].getPointA().getY());t.graphics.closePath();t.x=-p.x;t.y=-p.y};this.setChildIndex=function(a){d.setChildIndex(p,a)};this.getChildIndex=function(){return d.getChildIndex(p)};this.fallEffect=function(){createjs.Tween.get(p).to({y:CANVAS_HEIGHT,alpha:0},1500,createjs.Ease.cubicIn).call(function(){d.removeChild(p)})};this.getColor=function(){return r};this.setPosition=function(a,b){p.x=a;p.y=b};this.getPos=function(){return{x:p.x,y:p.y}};
this.getEdges=function(){return f};this.getLocalEdges=function(){return q};this.setEdges=function(a,b){q=[];f=[];e=[];g=[];for(var c=0;c<NUM_OF_EDGES_FOR_STACK;c++){q[c]=new CEdge(a[c].getPointA().getX(),a[c].getPointA().getY(),a[c].getPointB().getX(),a[c].getPointB().getY(),START_EDGES_POSITION[c].type);var d=new CEdge(a[c].getPointA().getX()+b.x,a[c].getPointA().getY()+b.y,a[c].getPointB().getX()+b.x,a[c].getPointB().getY()+b.y,START_EDGES_POSITION[c].type);START_EDGES_POSITION[c].type===EDGE_RIGHT_UP||
START_EDGES_POSITION[c].type===EDGE_LEFT_DOWN?e.push(d):g.push(d);f.push(d)}};this.edgesToString=function(a){console.log("------------"+a+"-------------");for(a=0;a<NUM_OF_EDGES_FOR_STACK;a++)console.log(f[a].toString())};this.limitLeftDown=function(){(p.x<=h[m].x||p.y>=h[m].y)&&this.resetStack(RIGHT_UP)};this.limitRightDown=function(){(p.x>=h[m].x||p.y>=h[m].y)&&this.resetStack(LEFT_UP)};this.limitLeftUp=function(){(p.x<=h[m].x||p.y<=h[m].y)&&this.resetStack(RIGHT_DOWN)};this.limitRightUp=function(){(p.x>=
h[m].x||p.y<=h[m].y)&&this.resetStack(LEFT_DOWN)};this.unload=function(){d.removeChild(p)};this.resetStack=function(a){m=a;l.set(DIRECTION_STACKS[m].x,DIRECTION_STACKS[m].y)};this.update=function(a){p.x+=l.getX()*a;p.y+=l.getY()*a;switch(m){case LEFT_DOWN:this.limitLeftDown();break;case RIGHT_DOWN:this.limitRightDown();break;case LEFT_UP:this.limitLeftUp();break;case RIGHT_UP:this.limitRightUp()}};this._init(a,c,b);return this}
function CTextPerfect(a){var c,b,d,f,e,g,k;this._init=function(){k=new createjs.Container;a.addChild(k);e=new createjs.Text(TEXT_PERFECT,"100px "+FONT_GAME,TEXT_COLOR);e.textAlign="center";g=new createjs.Text(TEXT_PERFECT,"100px "+FONT_GAME,TEXT_COLOR_STROKE);g.textAlign="center";g.outline=3;d=PERFECT_TEXT_START_POINT.x;f=PERFECT_TEXT_START_POINT.y-s_iOffsetY;c=PERFECT_TEXT_END_POINT.x;b=PERFECT_TEXT_END_POINT.y-s_iOffsetY;k.addChild(g,e);k.visible=!1};this.updatePoints=function(a,c){f=PERFECT_TEXT_START_POINT.y-
c;b=PERFECT_TEXT_END_POINT.y-c};this.animText=function(){k.x=d;k.y=f;k.visible=!0;k.alpha=1;createjs.Tween.get(k,{override:!0}).to({x:c,y:b,alpha:0},MS_PERFECT_TEXT,createjs.Ease.cubicOut).set({visible:!1})};this._init();return this};
