/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import mainScene from "./scene/mainScene"
import RouteLay from "./panels/RouteLay"
import ShipContainer from "./components/ShipContainer"
import targetSwitch from "./components/targetSwitch"
import infoLay from "./panels/infoLay"
import planLay from "./panels/planLay"
import SceneLayer from "./components/SceneLayer"
import buildTrip from "./panels/buildTrip"
import deskTrip from "./panels/deskTrip"
import dockPos from "./panels/dockPos"
import proTrip from "./panels/proTrip"
import resourceAlt from "./panels/resourceAlt"
import repeatMove from "./components/repeatMove"

export default class GameConfig {
    static init() {
        //注册Script或者Runtime引用
        let reg = Laya.ClassUtils.regClass;
		reg("scene/mainScene.js",mainScene);
		reg("panels/RouteLay.js",RouteLay);
		reg("components/ShipContainer.js",ShipContainer);
		reg("components/targetSwitch.js",targetSwitch);
		reg("panels/infoLay.js",infoLay);
		reg("panels/planLay.js",planLay);
		reg("components/SceneLayer.js",SceneLayer);
		reg("panels/buildTrip.js",buildTrip);
		reg("panels/deskTrip.js",deskTrip);
		reg("panels/dockPos.js",dockPos);
		reg("panels/proTrip.js",proTrip);
		reg("panels/resourceAlt.js",resourceAlt);
		reg("components/repeatMove.js",repeatMove);
    }
}
GameConfig.width = 640;
GameConfig.height = 960;
GameConfig.scaleMode ="showall";
GameConfig.screenMode = "horizontal";
GameConfig.alignV = "top";
GameConfig.alignH = "center";
GameConfig.startScene = "Main.scene";
GameConfig.sceneRoot = "";
GameConfig.debug = true;
GameConfig.stat = false;
GameConfig.physicsDebug = true;
GameConfig.exportSceneToJson = true;

GameConfig.init();
